name: Arduino Linter

on:
  push:
    paths:
      - 'arduino/*.ino'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
