name: Build LaTeX document
on:
  push:
    paths:
      - 'documents/ws.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
         root_file: 'documents/ws.tex'
         post_compile: "mv ws.pdf documents/ws.pdf"
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: LaTexCompiler
          message: 'Compiled LaTeX into PDF, updated README'
          add: '["*.pdf","*md"]'
